import { useEffect, useState } from 'react';
import { Area, AreaChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowDownRight, ArrowRight, Boxes, BrainCircuit, CircleDollarSign, Cpu, Database, Gauge, Layers3, Plus, ShieldAlert, Sparkles, Zap } from 'lucide-react';
import { api, type DashboardData, type SessionInfo, type Workload } from '../api';
import { IntegrationNotice, PageHeader, SectionHeading, StatusBadge } from '../components/ui';

const tones = ['#22b995', '#6381f6', '#f0ad53', '#ad83ee'];
export function OverviewPage({ data, busy, session, refresh, notify }: { data: { dashboard?: DashboardData; workloads: Workload[] }; busy: boolean; session: SessionInfo; refresh: () => Promise<void>; notify: (title: string, tone?: 'success' | 'error' | 'info') => void }) {
  const [range, setRange] = useState('7d');
  const [dashboard, setDashboard] = useState(data.dashboard);
  useEffect(() => { setDashboard(data.dashboard); }, [data.dashboard]);
  useEffect(() => { api.dashboard(range).then(setDashboard).catch(() => undefined); }, [range]);
  const refreshOverview = async () => {
    await refresh();
    try {
      setDashboard(await api.dashboard(range));
      notify('Overview refreshed from workspace data', 'info');
    } catch (error) {
      notify(error instanceof Error ? error.message : 'Could not refresh overview.', 'error');
    }
  };
  const summary = dashboard?.summary;
  const chart = dashboard?.resource_series || [];
  const cards = [
    { label: 'Registered workloads', value: summary?.workloads ?? '—', note: 'Across your organization', icon: Layers3, color: 'mint' },
    { label: 'Active deployments', value: summary?.deployments ?? '—', note: 'Demo endpoints · no live cloud', icon: Boxes, color: 'blue' },
    { label: 'Estimated monthly spend', value: summary ? `$${summary.estimated_monthly_spend_usd.toLocaleString()}` : '—', note: 'Illustrative sample · not billing', icon: CircleDollarSign, color: 'amber' },
    { label: 'Allocation efficiency', value: summary ? `${summary.allocation_efficiency}%` : '—', note: `${summary?.optimization_opportunities ?? 0} opportunities detected`, icon: Gauge, color: 'violet' },
  ];
  return <div className="page-stack">
    <PageHeader eyebrow="MONDAY, OCTOBER 04 · ORGANIZATION OVERVIEW" title={`Good morning, ${session.user.name.split(' ')[0]}.`} subtitle="Your workload context, resource fit and operational signals in one place." actions={<><button className="button button-secondary" onClick={() => void refreshOverview()} disabled={busy}><Activity size={15} /> Refresh</button><a className="button button-primary" href="/workloads"><Plus size={16} /> Register workload</a></>} />
    <div className="demo-banner"><span className="demo-shield"><ShieldAlert size={16} /></span><span><b>Demo workspace</b><small>Illustrative workloads, telemetry and costs. No cloud account is connected; actual spending is unavailable.</small></span><a href="/settings">Integration status <ArrowRight size={14} /></a><span className="demo-stamp">SIMULATED DATA</span></div>
    <div className="metric-grid">{cards.map((card, index) => { const Icon = card.icon; return <article className={`metric-card metric-${card.color}`} key={card.label}><div className="metric-top"><span>{card.label}</span><span className={`metric-icon ${card.color}`}><Icon size={17} /></span></div><div className="metric-value">{busy ? <i className="skeleton-inline" /> : card.value}</div><div className="metric-note">{card.note}</div><div className="metric-index">0{index + 1}</div></article>; })}</div>
    <div className="dashboard-grid">
      <section className="panel chart-panel"><div className="panel-header"><div><SectionHeading title="Resource utilization" detail="CPU and memory · sample telemetry" /></div><select className="select-compact" value={range} onChange={e => setRange(e.target.value)} aria-label="Chart date range"><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option></select></div><div className="chart-legend"><span><i className="legend-dot legend-cpu" /> CPU utilization</span><span><i className="legend-dot legend-memory" /> Memory utilization</span><span className="legend-demo">SAMPLE DATA</span></div><div className="chart-wrap chart-large"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{ top: 10, right: 12, left: -18, bottom: 0 }}><CartesianGrid stroke="#edf0f3" strokeDasharray="4 5" vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: '#99a4af', fontSize: 11 }} dy={12} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#99a4af', fontSize: 11 }} domain={[0, 100]} ticks={[0, 25, 50, 75, 100]} /><Tooltip contentStyle={{ borderRadius: 10, borderColor: '#edf0f3', boxShadow: '0 8px 24px #13223812' }} formatter={(value) => [`${value}%`, '']} /><Line type="monotone" dataKey="cpu" name="CPU" stroke="#26b990" strokeWidth={2.5} dot={false} activeDot={{ r: 4 }} /><Line type="monotone" dataKey="memory" name="Memory" stroke="#7188f6" strokeWidth={2.5} dot={false} activeDot={{ r: 4 }} /></LineChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="status-dot status-dot-mint" /> Utilization remains within the demo policy envelope</span><span>Refreshed just now</span></div></section>
      <section className="panel allocation-panel"><div className="panel-header"><SectionHeading title="Workload mix" detail="Share by workload category" /><button className="dots-button" title="View workloads" onClick={() => { window.location.href = '/workloads'; }}>···</button></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={dashboard?.workload_mix || []} dataKey="value" nameKey="name" innerRadius={61} outerRadius={82} paddingAngle={4} stroke="none">{(dashboard?.workload_mix || []).map((_, i) => <Cell key={i} fill={tones[i % tones.length]} />)}</Pie><Tooltip formatter={(value) => [`${value}%`, 'Share']} /></PieChart></ResponsiveContainer><div className="donut-center"><b>{summary?.workloads ?? 0}</b><span>workloads</span></div></div><div className="mix-legend">{(dashboard?.workload_mix || []).map((item, i) => <div key={item.name}><span><i style={{ background: tones[i % tones.length] }} />{item.name}</span><b>{item.value}%</b></div>)}</div><a href="/workloads" className="panel-link">Explore workloads <ArrowRight size={14} /></a></section>
    </div>
    <div className="dashboard-grid dashboard-grid-bottom">
      <section className="panel cost-panel"><div className="panel-header"><SectionHeading title="Cost trend" detail="Illustrative daily estimate · USD" /><span className="tiny-flag"><CircleDollarSign size={13} /> ESTIMATE</span></div><div className="cost-figure"><b>$1,840</b><span className="trend-positive"><ArrowDownRight size={14} /> 6.2%</span><small>estimated · current period</small></div><div className="chart-wrap chart-cost"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{ top: 6, right: 4, left: -18, bottom: 0 }}><defs><linearGradient id="costFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#24b996" stopOpacity={0.18} /><stop offset="100%" stopColor="#24b996" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="#edf0f3" strokeDasharray="4 5" vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: '#9ba7b2', fontSize: 10 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#9ba7b2', fontSize: 10 }} /><Tooltip formatter={(value) => [`$${value}`, 'Estimate']} /><Area type="monotone" dataKey="cost" stroke="#24b996" strokeWidth={2} fill="url(#costFill)" /></AreaChart></ResponsiveContainer></div><IntegrationNotice title="Actual billing is not connected" detail="This estimate is sample data; connect a billing source before making spend decisions." /></section>
      <section className="panel workload-panel"><div className="panel-header"><SectionHeading title="Workloads to watch" detail="Recent registrations and activity" /><a href="/workloads" className="text-link">View all <ArrowRight size={14} /></a></div><div className="workload-mini-list">{(data.workloads || []).slice(0, 4).map((item, i) => <div className="workload-mini" key={item.id}><span className={`workload-mini-icon tone-${i % 4}`}>{i === 0 ? <BrainCircuit size={16} /> : i === 1 ? <Cpu size={16} /> : i === 2 ? <Zap size={16} /> : <Database size={16} />}</span><span className="workload-mini-info"><b>{item.name}</b><small>{item.task_type} · {item.framework}</small></span><StatusBadge tone={item.status === 'Running' ? 'success' : item.is_demo ? 'demo' : 'neutral'}>{item.status}</StatusBadge></div>)}{!data.workloads.length && <div className="empty-state">Your registered workloads will appear here.</div>}</div></section>
      <section className="panel signals-panel"><div className="panel-header"><SectionHeading title="Operational signals" detail="Signals are scoped to demo telemetry" /><span className="signal-pulse"><i /> DEMO</span></div><div className="signal-list"><div className="signal-row"><span className="signal-icon signal-warn"><ShieldAlert size={15} /></span><span><b>{summary?.open_alerts ?? 0} open alerts</b><small>Budget and latency policies</small></span><a href="/alerts" aria-label="Open alerts">↗</a></div><div className="signal-row"><span className="signal-icon signal-info"><Sparkles size={15} /></span><span><b>{summary?.optimization_opportunities ?? 0} cost opportunities</b><small>Potential estimate · review first</small></span><a href="/optimizer" aria-label="Open optimization">↗</a></div><div className="signal-row"><span className="signal-icon signal-safe"><Layers3 size={15} /></span><span><b>{summary?.pipelines ?? 0} pipeline runs in progress</b><small>Simulated workflow state</small></span><a href="/pipelines" aria-label="Open pipelines">↗</a></div></div><div className="signal-footer"><span className="signal-footer-mark"><Sparkles size={13} /></span>Context engine is operating on workload requirements and rules v1.0.</div></section>
    </div>
  </div>;
}
