import { useRef, useState } from 'react';
import { Activity, ArrowRight, Check, ChevronDown, CloudUpload, FileText, Filter, Plus, Search, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import { api, type Analysis, type SessionInfo, type Workload, type WorkloadInput } from '../api';
import { WorkloadForm } from '../components/WorkloadForm';
import { IntegrationNotice, PageHeader, StatusBadge } from '../components/ui';

export function WorkloadsPage({ data, busy, refresh, notify, session }: { data: { workloads: Workload[] }; busy: boolean; refresh: () => Promise<void>; notify: (title: string, tone?: 'success' | 'error' | 'info') => void; session: SessionInfo }) {
  const [creating, setCreating] = useState(false);
  const [filter, setFilter] = useState('');
  const [taskFilter, setTaskFilter] = useState('All types');
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [analyzing, setAnalyzing] = useState('');
  const [imported, setImported] = useState<Record<string, unknown> | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const visible = data.workloads.filter(w => (!filter || `${w.name} ${w.task_type} ${w.framework}`.toLowerCase().includes(filter.toLowerCase())) && (taskFilter === 'All types' || w.task_type.toLowerCase().includes(taskFilter.toLowerCase())));
  const save = async (value: WorkloadInput) => { await api.createWorkload(value); setCreating(false); await refresh(); notify('Workload registered', 'success'); };
  const analyze = async (id: string) => { setAnalyzing(id); try { setAnalysis(await api.analyze(id)); notify('Workload analysis saved', 'success'); } catch (error) { notify(error instanceof Error ? error.message : 'Analysis failed.', 'error'); } finally { setAnalyzing(''); } };
  const upload = async (file?: File) => {
    if (!file) return;
    const body = new FormData(); body.append('file', file);
    try { const response = await fetch('/api/v1/workloads/upload', { method: 'POST', credentials: 'same-origin', body }); const result = await response.json(); if (!response.ok) throw new Error(result.detail || 'Upload failed.'); setImported(result); notify('Configuration parsed · review before saving', 'info'); }
    catch (error) { notify(error instanceof Error ? error.message : 'Could not parse configuration.', 'error'); }
    if (inputRef.current) inputRef.current.value = '';
  };
  const saveImport = async () => { if (!imported?.extracted) return; try { await api.createWorkload(imported.extracted as WorkloadInput); setImported(null); await refresh(); notify('Imported requirements saved as a workload', 'success'); } catch (error) { notify(error instanceof Error ? error.message : 'Could not save the imported workload.', 'error'); } };
  return <div className="page-stack">
    <PageHeader eyebrow="WORKLOAD INVENTORY / CONTEXT ANALYSIS" title="Workload Analysis" subtitle="Register the shape of your ML work. AstraDeploy turns requirements into explainable resource profiles." actions={<><button className="button button-secondary" onClick={() => inputRef.current?.click()}><CloudUpload size={16} />Import config</button><button className="button button-primary" onClick={() => setCreating(v => !v)}><Plus size={16} />New workload</button></>} />
    <input ref={inputRef} type="file" accept=".yaml,.yml,.json,.txt,Dockerfile" className="sr-only" onChange={e => upload(e.target.files?.[0])} />
    <div className="demo-banner demo-banner-compact"><span className="demo-shield"><FileText size={15} /></span><span><b>Analysis mode</b><small>Requirement-based estimates only. Historical utilization and connected monitoring are not available.</small></span><span className="demo-stamp">{session.user.role.toUpperCase()}</span></div>
    {imported && <div className="import-review panel"><div className="import-review-head"><span><CloudUpload size={18} /><b>Review imported configuration</b></span><button className="icon-button" aria-label="Close import" onClick={() => setImported(null)}><X size={16} /></button></div><div className="import-grid">{Object.entries((imported.extracted || {}) as Record<string, unknown>).map(([key, value]) => <label className="field" key={key}><span>{key.replaceAll('_', ' ')}</span><input value={String(value)} readOnly /></label>)}</div><p>{String(imported.analysis_note || '')} · {String(imported.filename || '')} · {String(imported.bytes || 0)} bytes</p><button className="button button-primary" onClick={saveImport}><Check size={15} />Save reviewed workload</button></div>}
    {creating && <div className="panel create-workload-panel"><div className="modal-heading"><div><span className="eyebrow">NEW WORKLOAD / REQUIREMENTS</span><h2>Register a workload</h2><p>Start with what the workload needs. You can revise it later.</p></div><button className="icon-button" onClick={() => setCreating(false)} aria-label="Close form"><X size={17} /></button></div><WorkloadForm onSubmit={save} onCancel={() => setCreating(false)} submitLabel="Register workload" /></div>}
    <div className="workload-summary-grid"><div className="summary-tile"><span className="summary-icon"><Activity size={16} /></span><span><small>Total registered</small><b>{data.workloads.length}</b></span><span className="summary-tail">workloads</span></div><div className="summary-tile"><span className="summary-icon summary-blue"><Sparkles size={16} /></span><span><small>Rule analyses</small><b>{data.workloads.filter(x => x.status === 'Analyzed').length}</b></span><span className="summary-tail">available</span></div><div className="summary-tile"><span className="summary-icon summary-amber"><CloudUpload size={16} /></span><span><small>Live sources</small><b>0</b></span><span className="summary-tail">connected</span></div></div>
    <section className="panel workloads-table-panel"><div className="table-toolbar"><div><h2>Registered workloads</h2><p>{visible.length} shown · data is organization-scoped</p></div><div className="table-actions"><label className="table-search"><Search size={15} /><input placeholder="Find workload…" value={filter} onChange={e => setFilter(e.target.value)} /></label><label className="filter-select"><Filter size={14} /><select value={taskFilter} onChange={e => setTaskFilter(e.target.value)}><option>All types</option><option>training</option><option>inference</option><option>batch</option><option>preprocessing</option></select><ChevronDown size={13} /></label></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Workload</th><th>Category</th><th>Framework</th><th>Resource profile</th><th>Status</th><th>Source</th><th>Actions</th></tr></thead><tbody>{visible.map((workload, i) => <tr key={workload.id}><td><div className="table-primary"><span className={`table-icon table-icon-${i % 4}`}><Activity size={15} /></span><span><b>{workload.name}</b><small>Updated {new Date(workload.created_at).toLocaleDateString()}</small></span></div></td><td><span className="table-secondary">{workload.task_type}</span></td><td><span className="framework-label">{workload.framework}</span></td><td><span className="resource-spec">{workload.requirements.cpu_cores ?? '—'} CPU · {workload.requirements.memory_gb ?? '—'} GB{Number(workload.requirements.gpu_count || 0) ? ` · ${workload.requirements.gpu_count} GPU` : ''}</span></td><td><StatusBadge tone={workload.status === 'Running' ? 'success' : workload.status === 'Analyzed' ? 'info' : 'neutral'}>{workload.status}</StatusBadge></td><td><StatusBadge tone={workload.is_demo ? 'demo' : 'neutral'}>{workload.is_demo ? 'Sample' : 'Registered'}</StatusBadge></td><td><button className="table-action" onClick={() => analyze(workload.id)} disabled={analyzing === workload.id}>{analyzing === workload.id ? 'Analyzing…' : 'Analyze'} <ArrowRight size={13} /></button></td></tr>)}{visible.length === 0 && <tr><td colSpan={7}><div className="table-empty">{busy ? 'Loading workload data…' : 'No workloads match this filter.'}<button className="text-link" onClick={() => { setFilter(''); setTaskFilter('All types'); }}>Clear filters</button></div></td></tr>}</tbody></table></div><div className="table-footer"><span>Showing {visible.length} of {data.workloads.length} workloads</span><span><SlidersHorizontal size={14} /> Sort: recently updated <ChevronDown size={12} /></span></div></section>
    {analysis && <section className="analysis-result panel"><div className="analysis-result-head"><span className="analysis-success-icon"><Check size={16} /></span><div><b>Workload analysis saved</b><small>{analysis.classification} · {analysis.source} · rule set v1.0</small></div><StatusBadge tone="demo">{analysis.is_demo ? 'SAMPLE WORKLOAD' : 'USER INPUT'}</StatusBadge></div><div className="analysis-stats">{Object.entries(analysis.demand).map(([key, value]) => <div key={key}><small>{key.replaceAll('_', ' ')}</small><b>{value}{key === 'cpu_cores' ? ' vCPU' : key === 'memory_gb' || key === 'storage_gb' ? ' GB' : ''}</b></div>)}</div><div className="analysis-bottleneck"><b>Risks & notes</b><ul>{[...analysis.bottlenecks, ...analysis.limitations].map((note, i) => <li key={i}>{note}</li>)}</ul></div><a href="/advisor" className="button button-secondary">Compare resource plans <ArrowRight size={14} /></a></section>}
    <IntegrationNotice title="No monitoring source connected" detail="Historical utilization, workload variability and time-series demand forecasts need a configured Prometheus/Grafana-compatible source." />
  </div>;
}
